modLoader = "javafml"
loaderVersion = "[@LOADER_MAJOR@,)"
issueTrackerURL = "https://github.com/Creatures-5/CreateMachinery/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "create_machinery"
version = "${version}"
displayName = "Create: Immersive Machinery"
displayURL = "https://modrinth.com/project/create-immersive-machinery"
authors = "Creatures-5"
description = "A fork of Immersive Machinery aimed at integration with Create."
logoFile = "icon.png"
itemIcon = "create_machinery:tunnel_digger"

[[dependencies.create_machinery]]
modId = "minecraft"
mandatory = true
versionRange = "[@MINECRAFT_VERSION@,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_machinery]]
modId = "forge"
mandatory = true
versionRange = "[@LOADER_MAJOR@,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_machinery]]
modId = "immersive_aircraft"
mandatory = true
versionRange = "[1.2.0,)"
ordering = "AFTER"
side = "BOTH"